=== BiAffectBridge/mobile-client-json/schemas/v1/biaffect/MotionSample.json
{
  "$id" : "https://biaffect.github.io/biaffectsdk/schemas/v1/MotionSample.json",
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "array",
  "title" : "MotionSample",
  "description" : "An array of motion sensor samples.",
  "items" : {
    "type" : "object",
    "properties" : {
      "uptime" : {
        "type" : "number",
        "description" : "Clock time. This is the system uptime that is reported with a sample while the app is in the foreground."
      },
      "timestamp" : {
        "type" : "number",
        "description" : "A duration in seconds relative to when the recorder was started."
      },
      "stepPath" : {
        "type" : "string",
        "description" : "An identifier marking the response attempt including display state."
      },
      "timestampDate" : {
        "type" : "string",
        "description" : "The date timestamp when step path was changed.",
        "format" : "date-time"
      },
      "sensorType" : {
        "type" : "string",
        "description" : "The sensor type for this record sample. If `null` then this sample is a `stepPath` change marker.",
        "enum" : [
          "accelerometer",
          "gyro",
          "userAcceleration"
        ]
      },
      "x" : {
        "type" : "number",
        "description" : "The `x` component of the vector measurement for this sensor sample."
      },
      "y" : {
        "type" : "number",
        "description" : "The `y` component of the vector measurement for this sensor sample."
      },
      "z" : {
        "type" : "number",
        "description" : "The `z` component of the vector measurement for this sensor sample."
      },
      "vectorMagnitude" : {
        "type" : "number",
        "description" : "The calculated vector magnitude used to determine whether or not the device was shaken. (`sensorType==userAcceleration`)"
      }
    },
    "required" : [
      "stepPath",
      "uptime",
      "timestamp"
    ],
    "additionalProperties" : false,
    "examples" : [
        {
          "stepPath" : "starting",
          "timestamp" : 0,
          "timestampDate" : "2022-06-29T12:41:20.029-07:00",
          "uptime" : 1289650.419528791
        },
        {
          "stepPath" : "attempt/3/showing/blue",
          "timestamp" : 28.606888458365574,
          "timestampDate" : "2022-06-29T12:41:48.636-07:00",
          "uptime" : 1289679.0264153329
        },
        {
          "stepPath" : "attempt/3/showing/blue",
          "uptime" : 1289679.0275513744,
          "timestamp" : 28.608022583415732,
          "sensorType" : "userAcceleration",
          "x" : -0.00084100663661956787,
          "y" : 0.0043393969535827637,
          "z" : 0.010767042636871338,
          "vectorMagnitude" : 0.011639023379468177
        },
        {
          "uptime" : 1289679.0255373744,
          "timestamp" : 28.606008583330549,
          "stepPath" : "attempt/3/showing/blue",
          "sensorType" : "accelerometer",
          "x" : 0.06011962890625,
          "y" : -0.43389892578125,
          "z" : -0.8861541748046875
        },
        {
          "uptime" : 1289679.0335633743,
          "timestamp" : 28.614034583326429,
          "stepPath" : "attempt/3/showing/blue",
          "sensorType" : "gyro",
          "x" : -0.011590609326958656,
          "y" : 0.00079788308357819915,
          "z" : 0.0056229983456432819
        }
    ]
  }
}

=== BiAffectBridge/mobile-client-json/examples/v1/biaffect/KeyboardSession-archive/motion.json
[
{
  "stepPath" : "",
  "timestamp" : 0,
  "timestampDate" : "2022-07-15T14:45:01.085-07:00",
  "uptime" : 1579461.2372061252
},
{
  "uptime" : 1579461.2615294168,
  "timestamp" : 0.02432329161092639,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0420074462890625,
  "y" : -0.5089874267578125,
  "z" : -0.8473052978515625
},
{
  "uptime" : 1579461.3619924167,
  "timestamp" : 0.12478629150427878,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.04302978515625,
  "y" : -0.498992919921875,
  "z" : -0.8492279052734375
},
{
  "uptime" : 1579461.4624874168,
  "timestamp" : 0.22528129164129496,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0396270751953125,
  "y" : -0.5098876953125,
  "z" : -0.8520965576171875
},
{
  "uptime" : 1579461.5629514167,
  "timestamp" : 0.32574529154226184,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.046356201171875,
  "y" : -0.5068511962890625,
  "z" : -0.8645782470703125
},
{
  "uptime" : 1579461.6634154168,
  "timestamp" : 0.42620929167605937,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.029632568359375,
  "y" : -0.5106658935546875,
  "z" : -0.8446044921875
},
{
  "uptime" : 1579461.7639094167,
  "timestamp" : 0.52670329157263041,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.00244140625,
  "y" : -0.5070343017578125,
  "z" : -0.813385009765625
},
{
  "uptime" : 1579461.8643734169,
  "timestamp" : 0.62716729170642793,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0092620849609375,
  "y" : -0.50189208984375,
  "z" : -0.8580780029296875
},
{
  "uptime" : 1579461.9648674168,
  "timestamp" : 0.72766129160299897,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0237884521484375,
  "y" : -0.477630615234375,
  "z" : -0.8379058837890625
},
{
  "uptime" : 1579462.0653314167,
  "timestamp" : 0.82812529150396585,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.004974365234375,
  "y" : -0.51025390625,
  "z" : -0.8170013427734375
},
{
  "uptime" : 1579462.1658254168,
  "timestamp" : 0.92861929163336754,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0507354736328125,
  "y" : -0.503631591796875,
  "z" : -0.8808135986328125
},
{
  "uptime" : 1579462.266329,
  "timestamp" : 1.0291228748392314,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0186920166015625,
  "y" : -0.4894256591796875,
  "z" : -0.8217620849609375
},
{
  "uptime" : 1579462.3668240001,
  "timestamp" : 1.1296178749762475,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0225982666015625,
  "y" : -0.5258941650390625,
  "z" : -0.8658294677734375
},
{
  "uptime" : 1579462.467288,
  "timestamp" : 1.2300818748772144,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0460052490234375,
  "y" : -0.52166748046875,
  "z" : -0.8307647705078125
},
{
  "uptime" : 1579462.5677510002,
  "timestamp" : 1.3305448750033975,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.05780029296875,
  "y" : -0.5233154296875,
  "z" : -0.8289794921875
},
{
  "uptime" : 1579462.6682460001,
  "timestamp" : 1.431039874907583,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.049713134765625,
  "y" : -0.532989501953125,
  "z" : -0.8383026123046875
},
{
  "uptime" : 1579462.7687100002,
  "timestamp" : 1.5315038750413805,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0472259521484375,
  "y" : -0.5334625244140625,
  "z" : -0.8153533935546875
},
{
  "uptime" : 1579462.8692040001,
  "timestamp" : 1.6319978749379516,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0380706787109375,
  "y" : -0.5337982177734375,
  "z" : -0.8542022705078125
},
{
  "uptime" : 1579462.969668,
  "timestamp" : 1.7324618748389184,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.011474609375,
  "y" : -0.4985198974609375,
  "z" : -0.817138671875
},
{
  "uptime" : 1579463.0701620001,
  "timestamp" : 1.8329558749683201,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : -0.004302978515625,
  "y" : -0.513702392578125,
  "z" : -0.8686065673828125
},
{
  "uptime" : 1579463.1706624168,
  "timestamp" : 1.9334562916774303,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.040557861328125,
  "y" : -0.5104217529296875,
  "z" : -0.8435516357421875
},
{
  "uptime" : 1579463.2711264167,
  "timestamp" : 2.0339202915783972,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0084381103515625,
  "y" : -0.5086517333984375,
  "z" : -0.8492431640625
},
{
  "uptime" : 1579463.3716204169,
  "timestamp" : 2.1344142917077988,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0339508056640625,
  "y" : -0.5076751708984375,
  "z" : -0.841766357421875
},
{
  "uptime" : 1579463.4720844168,
  "timestamp" : 2.2348782916087657,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.026611328125,
  "y" : -0.5203399658203125,
  "z" : -0.8361968994140625
},
{
  "uptime" : 1579463.5725794167,
  "timestamp" : 2.3353732915129513,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0240478515625,
  "y" : -0.52374267578125,
  "z" : -0.8404998779296875
},
{
  "uptime" : 1579463.6730434168,
  "timestamp" : 2.4358372916467488,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : -0.0080413818359375,
  "y" : -0.522857666015625,
  "z" : -0.851043701171875
},
{
  "uptime" : 1579463.7735374167,
  "timestamp" : 2.5363312915433198,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.024261474609375,
  "y" : -0.5220489501953125,
  "z" : -0.836456298828125
},
{
  "uptime" : 1579463.8740014168,
  "timestamp" : 2.6367952916771173,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.041534423828125,
  "y" : -0.521026611328125,
  "z" : -0.8675994873046875
},
{
  "uptime" : 1579463.9744654167,
  "timestamp" : 2.7372592915780842,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.024749755859375,
  "y" : -0.5269317626953125,
  "z" : -0.8109588623046875
},
{
  "uptime" : 1579464.0749594169,
  "timestamp" : 2.8377532917074859,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0452728271484375,
  "y" : -0.500701904296875,
  "z" : -0.8708343505859375
},
{
  "uptime" : 1579464.175461875,
  "timestamp" : 2.9382557498756796,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0167388916015625,
  "y" : -0.504730224609375,
  "z" : -0.8563995361328125
},
{
  "uptime" : 1579464.2759558752,
  "timestamp" : 3.0387497500050813,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0100860595703125,
  "y" : -0.473175048828125,
  "z" : -0.8771514892578125
},
{
  "uptime" : 1579464.3764198751,
  "timestamp" : 3.1392137499060482,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0253143310546875,
  "y" : -0.503662109375,
  "z" : -0.82110595703125
},
{
  "uptime" : 1579464.4769148752,
  "timestamp" : 3.2397087500430644,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.045654296875,
  "y" : -0.52752685546875,
  "z" : -0.8508453369140625
},
{
  "uptime" : 1579464.5773778751,
  "timestamp" : 3.3401717499364167,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0447540283203125,
  "y" : -0.5450286865234375,
  "z" : -0.8130645751953125
},
{
  "uptime" : 1579464.677872875,
  "timestamp" : 3.4406667498406023,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0273895263671875,
  "y" : -0.5364837646484375,
  "z" : -0.842193603515625
},
{
  "uptime" : 1579464.7783368751,
  "timestamp" : 3.5411307499743998,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0160369873046875,
  "y" : -0.547515869140625,
  "z" : -0.8214874267578125
},
{
  "uptime" : 1579464.878800875,
  "timestamp" : 3.6415947498753667,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.03363037109375,
  "y" : -0.550048828125,
  "z" : -0.8308258056640625
},
{
  "uptime" : 1579464.9792948752,
  "timestamp" : 3.7420887500047684,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : -0.0134124755859375,
  "y" : -0.5552978515625,
  "z" : -0.7884063720703125
},
{
  "uptime" : 1579465.0797588751,
  "timestamp" : 3.8425527499057353,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0522613525390625,
  "y" : -0.562408447265625,
  "z" : -0.8615875244140625
},
{
  "uptime" : 1579465.1803189167,
  "timestamp" : 3.9431127915158868,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.033111572265625,
  "y" : -0.5546722412109375,
  "z" : -0.811309814453125
},
{
  "uptime" : 1579465.2807829168,
  "timestamp" : 4.0435767916496843,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0424957275390625,
  "y" : -0.567474365234375,
  "z" : -0.834686279296875
},
{
  "uptime" : 1579465.3812769167,
  "timestamp" : 4.1440707915462554,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.1202545166015625,
  "y" : -0.5865936279296875,
  "z" : -0.804290771484375
},
{
  "uptime" : 1579465.4817409168,
  "timestamp" : 4.2445347916800529,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.074462890625,
  "y" : -0.541656494140625,
  "z" : -0.7865447998046875
},
{
  "uptime" : 1579465.5822359168,
  "timestamp" : 4.3450297915842384,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0268707275390625,
  "y" : -0.52874755859375,
  "z" : -0.826019287109375
},
{
  "uptime" : 1579465.6826999167,
  "timestamp" : 4.4454937914852053,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0395660400390625,
  "y" : -0.57440185546875,
  "z" : -0.826416015625
},
{
  "uptime" : 1579465.7831629168,
  "timestamp" : 4.5459567916113883,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0418548583984375,
  "y" : -0.54345703125,
  "z" : -0.8158416748046875
},
{
  "uptime" : 1579465.8836579167,
  "timestamp" : 4.6464517915155739,
  "stepPath" : "",
  "sensorType" : "accelerometer",
  "x" : 0.0510711669921875,
  "y" : -0.5830535888671875,
  "z" : -0.83380126953125
},
{
