=== BiAffectBridge/mobile-client-json/schemas/v0/WeatherResult.json
{
  "$id" : "https://raw.githubusercontent.com/Sage-Bionetworks/AssessmentModel-JsonSchema/main/schemas/WeatherResult.json",
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "definitions" : {

  },
  "description" : "",
  "properties" : {
    "airQuality" : {
      "$ref" : "ResultData.json#AirQualityServiceResult"
    },
    "endDate" : {
      "format" : "date-time",
      "type" : "string"
    },
    "identifier" : {
      "type" : "string"
    },
    "startDate" : {
      "format" : "date-time",
      "type" : "string"
    },
    "type" : {
      "$ref" : "ResultData.json#SerializableResultType",
      "const" : "weather"
    },
    "weather" : {
      "$ref" : "ResultData.json#WeatherServiceResult"
    }
  },
  "required" : [
    "identifier",
    "type",
    "startDate"
  ],
  "title" : "WeatherResult",
  "type" : "object"
}

=== BiAffectBridge/mobile-client-json/examples/v2/WeatherResult/WeatherResult_0.json
{
  "airQuality" : {
    "aqi" : 2,
    "category" : {
      "name" : "Moderate",
      "number" : 2
    },
    "identifier" : "airQuality",
    "provider" : "airNow",
    "startDate" : "2023-06-05T15:47:38.577-07:00"
  },
  "endDate" : "2023-06-05T15:47:38.577-07:00",
  "identifier" : "weather",
  "startDate" : "2023-06-05T15:47:38.577-07:00",
  "type" : "weather",
  "weather" : {
    "clouds" : 0.40000000000000002,
    "humidity" : 0.90000000000000002,
    "identifier" : "weather",
    "provider" : "openWeather",
    "startDate" : "2023-06-05T15:47:38.577-07:00",
    "temperature" : 20
  }
}
