=== BiAffectBridge/mobile-client-json/schemas/v1/ArchiveMap.json
{
  "$id" : "https://sage-bionetworks.github.io/mobile-client-json/schemas/v1/ArchiveMap.json",
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "title" : "ArchiveMap",
  "definitions" : {
    "AssessmentIdentifier" : {
      "$id" : "#AssessmentIdentifier",
      "type" : "object",
      "properties" : {
        "assessmentIdentifier": {
          "type": "string",
          "description": "The assessment identifier defined within the Bridge namespace for the assessment. This identifier will map to the participant timeline."
        },
        "assessmentRevision": {
          "type": "integer",
          "description": "The min assessment revision as defined within the Bridge namespace for this archive manifest."
        }
      },
      "required" : [
        "assessmentIdentifier",
        "assessmentRevision"
      ]
    },
    "AssessmentArchive" : {
      "$id" : "#AssessmentArchive",
      "type" : "object",
      "title" : "AssessmentArchive",
      "description" : "The mappings for a given assessment archive.",
      "allOf": [
        {
          "$ref": "#AssessmentIdentifier"
        }
      ],
      "additionalProperties": false,
      "properties" : {
        "organization" : {
          "type" : "string",
          "description" : "The name or description of the assessment developer's organization. This is included for readability, is not necessarily the official organization name, and should not be used for searches or identifying the assessment."
        },
        "taskIdentifier" : {
          "type" : "string",
          "description" : "The identifier assigned by the assessment developer. This identifier is unique only within the developer's framework namespace."
        },
        "versionString" : {
          "type" : "string",
          "description" : "The min assessment version as defined by the assessment developer for this archive manifest."
        },
        "files" : {
          "type" : "array",
          "description": "The list of the files included in the assessment archive.",
          "items": {
            "$ref": "#FileInfo"
          }
        }
      }
    },
    "FileInfo" : {
      "$id" : "#FileInfo",
      "type" : "object",
      "title" : "FileInfo",
      "description" : "Information about a given file within the archive.",
      "additionalProperties": false,
      "properties" : {
        "filename" : {
          "type" : "string",
          "description" : "The filename of the archive object. This should be unique within the manifest.",
          "format" : "uri-relative"
        },
        "description" : {
          "type": "string",
          "description": "Description of the file content."
        },
        "contentType" : {
          "type" : "string",
          "description" : "The content type of the file.",
          "default": "application/json"
        },
        "jsonSchema" : {
          "type" : "string",
          "description" : "The uri for the json schema if the content type is 'application/json'.",
          "format" : "uri"
        },
        "isRequired" : {
          "type" : "boolean",
          "description" : "Whether or not the file is required.",
          "default" : false
        },
        "deprecated" : {
          "type" : "boolean",
          "description" : "Whether or not the file is deprecated and included for reverse-compatibility to older services and/or applications.",
          "default" : false
        },
        "$comment" : {
          "type": "string"
        }
      },
      "required" : [
        "filename"
      ]
    },
    "AppInfo" : {
      "$id" : "#AppInfo",
      "type" : "object",
      "title" : "AppInfo",
      "description" : "Bridge App Information",
      "additionalProperties": false,
      "properties" : {
        "appId" : {
          "type" : "string",
          "description" : "Bridge 'APP ID' for the application that is sending the data."
        },
        "iOS" : {
          "type" : "integer",
          "description" : "The min version sent to Bridge to identify the version of the iOS application.",
          "default" : 0
        },
        "android" : {
          "type" : "integer",
          "description" : "The min version sent to Bridge to identify the version of the Android application.",
          "default" : 0
        },
        "assessments" : {
          "type" : "array",
          "description": "The list of assessments supported by this application.",
          "items": {
            "$ref" : "#AssessmentIdentifier"
          }
        },
        "allOf" : {
          "type": "array",
          "description": "A list of files that may be included in any assessment archive for *this* application. These files can be associated with the assessments within this application but are *not* inclusive to a different application that hosts the same assessment.",
          "items": {
            "$ref": "#FileInfo"
          }
        }
      },
      "required" : [
        "appId",
        "assessments"
      ]
    }
  },
  "properties": {
    "$id" : {
      "type": "string",
      "format": "uri"
    },
    "$schema" : {
      "type": "string",
      "format": "uri"
    },
    "allOf" : {
      "type": "array",
      "description": "A list of files that are included by default in all archives across all applications.",
      "items": {
        "$ref": "#FileInfo"
      }
    },
    "assessments" : {
      "type": "array",
      "description": "A list of assessment archives uniquely indexed by `assessmentIdentifier` and `assessmentRevision`.",
      "items": {
        "$ref": "#AssessmentArchive"
      }
    },
    "apps" : {
      "type": "array",
      "description": "A list of apps uniquely indexed by identifier and version.",
      "items": {
        "$ref": "#AppInfo"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "$id",
    "$schema",
    "assessments"
  ]
}

=== BiAffectBridge/mobile-client-json/archive-map.json
{
  "$id": "https://sage-bionetworks.github.io/mobile-client-json/archive-map.json",
  "$schema": "https://sage-bionetworks.github.io/mobile-client-json/schemas/v1/ArchiveMap.json",
  "allOf": [
    {
      "filename": "metadata.json",
      "contentType": "application/json",
      "description": "Metadata associated with this archive including a file manifest and version information.",
      "isRequired": true,
      "jsonSchema": "https://sage-bionetworks.github.io/mobile-client-json/schemas/v1/TaskMetadata.json"
    },
    {
      "filename": "taskResult.json",
      "contentType": "application/json",
      "description": "The polymorphism serialized result of running an assessment. This structure includes all the step results in the chronological order in which they were presented as well as asynchronous results that may be recorded across multiple steps.",
      "isRequired": false,
      "jsonSchema": "https://sage-bionetworks.github.io/mobile-client-json/schemas/v1/TaskResultObject.json"
    },
    {
      "filename": "answers.json",
      "contentType": "application/json",
      "description": "A file used by Exporter 2.0 to export Bridge 1.0 surveys to synapse.",
      "deprecated": true
    },
    {
      "filename": "info.json",
      "contentType": "application/json",
      "description": "A file used by Exporter 2.0 to export data to synapse.",
      "deprecated": true
    }
  ],
  "assessments" : [
    {
      "assessmentIdentifier" : "spelling",
      "assessmentRevision": 5,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "MTB Spelling Form 1",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    },
    {
      "assessmentIdentifier" : "fnamea",
      "assessmentRevision": 5,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "FNAME Learning Form 1",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    },
    {
      "assessmentIdentifier" : "fnameb",
      "assessmentRevision": 5,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "FNAME Test Form 1",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    },
    {
      "assessmentIdentifier" : "vocabulary",
      "assessmentRevision": 5,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "Vocabulary Form 1",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    },
    {
      "assessmentIdentifier" : "flanker",
      "assessmentRevision": 5,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "Flanker Inhibitory Control",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    },
    {
      "assessmentIdentifier" : "psm",
      "assessmentRevision": 6,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "Picture Sequence MemoryV1",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    },
    {
      "assessmentIdentifier" : "memory-for-sequences",
      "assessmentRevision": 7,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "MFS pilot 2",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    },
    {
      "assessmentIdentifier" : "dccs",
      "assessmentRevision": 6,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "Dimensional Change Card Sort",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    },
    {
      "assessmentIdentifier" : "number-match",
      "assessmentRevision": 4,
      "organization": "Northwestern (MTB)",
      "taskIdentifier": "Number Match",
      "versionString": "1.2.0",
      "files": [
        {
          "filename": "taskData.json",
          "contentType": "application/json",
          "isRequired": true,
          "jsonSchema": "https://github.com/MobileToolbox/MTBfx/blob/master/JSONschema/taskData_combinedSchema.json"
        }
      ]
    }
  ],
  "apps": [
    {
      "appId": "mobile-toolbox",
      "iOS": 0,
      "android": 0,
      "allOf": [
        {
          "filename": "motion.json",
          "description": "Motion sensor data recorded while running the assessment.",
          "contentType": "application/json",
          "isRequired": false,
          "jsonSchema": "https://sage-bionetworks.github.io/mobile-client-json/schemas/v1/MotionRecord.json"
        },
        {
          "filename": "weather.json",
          "description": "The most recent weather conditions for the participant's location when the assessment is started.",
          "contentType": "application/json",
          "isRequired": false,
          "jsonSchema": "https://sage-bionetworks.github.io/mobile-client-json/schemas/v1/WeatherResult.json"
        },
        {
          "filename": "microphone_levels.json",
          "description": "The microphone levels recorded while running the assessment.",
          "contentType": "application/json",
          "isRequired": false,
          "jsonSchema": "https://sage-bionetworks.github.io/mobile-client-json/schemas/v1/AudioLevelRecord.json"
        }
      ],
      "assessments": [
        {
          "assessmentIdentifier": "spelling",
          "assessmentRevision": 5
        },
        {
          "assessmentIdentifier" : "fnamea",
          "assessmentRevision": 5
        },
        {
          "assessmentIdentifier" : "fnameb",
          "assessmentRevision": 5
        },
        {
          "assessmentIdentifier" : "vocabulary",
          "assessmentRevision": 5
        },
        {
          "assessmentIdentifier" : "flanker",
          "assessmentRevision": 5
        },
        {
          "assessmentIdentifier" : "psm",
          "assessmentRevision": 6
        },
        {
          "assessmentIdentifier" : "memory-for-sequences",
          "assessmentRevision": 7
        },
        {
          "assessmentIdentifier" : "dccs",
          "assessmentRevision": 6
        },
        {
          "assessmentIdentifier" : "number-match",
          "assessmentRevision": 4
        }
      ]
    }
  ]
}
